// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewAccount struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type NewTransaction struct {
	Amount    float64 `json:"amount"`
	AccountID string  `json:"accountId"`
}

type Query struct {
}
