// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Mutation struct {
}

type NewAccount struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type NewTransaction struct {
	Amount    float64 `json:"amount"`
	AccountID string  `json:"accountId"`
}

type Query struct {
}

type Transaction struct {
	ID        string     `json:"id"`
	Amount    float64    `json:"amount"`
	Accounts  []*Account `json:"accounts"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
}
